config/routes.rb
# frozen_string_literal: true

# OVERRIDE Hyrax 2.9.0 to add featured collection routes

require 'sidekiq/web' if ENV.fetch('HYRAX_ACTIVE_JOB_QUEUE', 'sidekiq') == 'sidekiq'

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  # Health check endpoint for load balancers (no auth required)
  get '/health', to: 'health#show'

  resources :identity_providers
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  concern :iiif_search, BlacklightIiifSearch::Routes.new
  concern :oai_provider, BlacklightOaiProvider::Routes.new
  mount WillowSword::Engine => '/sword'

  mount Hyrax::IiifAv::Engine, at: '/'
  mount IiifPrint::Engine, at: '/'
  mount Riiif::Engine => 'images', as: :riiif if Hyrax.config.iiif_image_server?

  authenticate :user, ->(u) { u.superadmin? || u.admin? } do
    queue = ENV.fetch('HYRAX_ACTIVE_JOB_QUEUE', 'sidekiq')
    case queue
    when 'sidekiq'
      mount Sidekiq::Web => '/jobs'
    when 'good_job'
      mount GoodJob::Engine => '/jobs'
    end
  end

  if ActiveModel::Type::Boolean.new.cast(ENV.fetch('HYKU_MULTITENANT', false))
    constraints host: Account.admin_host do
      get '/account/sign_up' => 'account_sign_up#new', as: 'new_sign_up'
      post '/account/sign_up' => 'account_sign_up#create'
      get '/', to: 'splash#index', as: 'splash'

      # pending https://github.com/projecthydra-labs/hyrax/issues/376
      get '/dashboard', to: redirect('/')

      namespace :proprietor do
        resources :accounts
        resources :users do
          member do
            post :become
          end
        end
      end
    end
  end

  get 'status', to: 'status#index'

  # routes for the  api
  namespace :api, defaults: { format: :json } do
    resource :sushi do
      collection do
        get 'r51/status', to: 'sushi#server_status'
        get 'r51/reports', to: 'sushi#report_list'
        get 'r51/reports/pr', to: 'sushi#platform_report'
        get 'r51/reports/pr_p1', to: 'sushi#platform_usage'
        get 'r51/reports/ir', to: 'sushi#item_report'
      end
    end
  end

  mount BrowseEverything::Engine => '/browse'

  resource :site, only: [:update] do
    resource :labels, only: %i[edit update]
    resources :roles, only: %i[index update]
  end

  root 'hyrax/homepage#index'

  devise_for :users, skip: [:omniauth_callbacks], controllers: { invitations: 'hyku/invitations',
                                                                 registrations: 'hyku/registrations',
                                                                 omniauth_callbacks: 'users/omniauth_callbacks' }
  as :user do
    resources :single_signon, only: [:index]

    Devise.omniauth_providers.each do |provider|
      path_prefix = '/users/auth'
      match "#{path_prefix}/#{provider}/:id",
        to: "users/omniauth_callbacks#passthru",
        as: "user_#{provider}_omniauth_authorize",
        via: OmniAuth.config.allowed_request_methods

      get "#{path_prefix}/#{provider}/:id/metadata", to: "users/omniauth_callbacks#passthru", as: "user_#{provider}_omniauth_metadata"

      match "#{path_prefix}/#{provider}/:id/callback",
        to: "users/omniauth_callbacks##{provider}",
        as: "user_#{provider}_omniauth_callback",
        via: [:get, :post]
    end
  end

  mount Qa::Engine => '/authorities'

  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'
  mount Hyrax::Engine, at: '/'
  mount Bulkrax::Engine, at: '/' if Hyku.bulkrax_enabled?
  mount HykuKnapsack::Engine, at: '/'
  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  curation_concerns_basic_routes

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :oai_provider

    concerns :searchable
    concerns :range_searchable
  end

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
    concerns :iiif_search
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  namespace :admin do
    resource :account, only: %i[edit update]
    resource :work_types, only: %i[edit update]
    resources :users, only: [:index, :destroy] do
      post 'activate', on: :member
      delete 'remove_role/:role_id', on: :member, to: 'users#remove_role', as: :remove_role
    end
    resources :groups do
      member do
        get :remove
      end

      resources :users, only: %i[index create destroy], param: :user_id, controller: 'group_users'
      resources :roles, only: %i[index create destroy], param: :role_id, controller: 'group_roles'
    end
    post "roles_service/:job_name_key", to: "roles_service#update_roles", as: :update_roles
    get "roles_service", to: "roles_service#index", as: :roles_service_jobs
  end

  # OVERRIDE here to add featured collection routes
  scope module: 'hyrax' do
    # Generic collection routes
    resources :collections, only: [] do
      member do
        resource :featured_collection, only: %i[create destroy]
      end
    end
    resources :featured_collection_lists, path: 'featured_collections', only: :create
  end

  get 'all_collections' => 'hyrax/homepage#all_collections', as: :all_collections

  # Upload a collection thumbnail
  post "/dashboard/collections/:id/delete_uploaded_thumbnail",
       to: "hyrax/dashboard/collections#delete_uploaded_thumbnail",
       as: :delete_uploaded_thumbnail

  if ENV.fetch('HYRAX_FLEXIBLE', false)
    # Metadata profiles routes
    resources :metadata_profiles, except: [:update, :show, :destroy] do
      collection { post :import }
      get 'export'
    end
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < AdminController
    before_action :ensure_admin!, except: [:remove_role]
    before_action :load_user, only: [:destroy]

    # NOTE: User creation/invitations handled by devise_invitable

    # Delete a user from the site
    def destroy
      if @user.present? && @user.roles.destroy_all
        redirect_to hyrax.admin_users_path, notice: t('hyrax.admin.users.destroy.success', user: @user)
      else
        redirect_to hyrax.admin_users_path, flash: { error: t('hyrax.admin.users.destroy.failure', user: @user) }
      end
    end

    def activate
      user = User.find(params[:id])
      user.password = ENV.fetch('HYKU_USER_DEFAULT_PASSWORD', 'password')

      if user.save && user.accept_invitation!
        redirect_to hyrax.admin_users_path, notice: t('hyrax.admin.users.activate.success', user:)
      else
        redirect_to hyrax.admin_users_path, flash: { error: t('hyrax.admin.users.activate.failure', user:) }
      end
    end

    def remove_role
      authorize! :edit, User

      user = User.find(params[:id])
      role = Role.find(params[:role_id])

      if user && role && user.roles.include?(role)
        user.remove_role(role.name)
        flash[:notice] = "Role '#{role.name}' was successfully removed from user #{user.email}."
      else
        flash[:alert] = "Failed to remove role from user #{user.email}."
      end

      redirect_back(fallback_location: root_path)
    end

    private

    def load_user
      @user = User.from_url_component(params[:id])
    end
  end
end

app/controllers/proprietor/users_controller.rb
# frozen_string_literal: true

module Proprietor
  class UsersController < ProprietorController
    before_action :ensure_admin!

    before_action :find_user, only: %i[show edit update destroy]
    load_and_authorize_resource

    # GET /users
    # GET /users.json
    def index
      authorize! :manage, User
      add_breadcrumb t(:'hyrax.controls.home'), root_path
      add_breadcrumb t(:'hyrax.admin.sidebar.users'), proprietor_users_path
    end

    # GET /users/1
    # GET /users/1.json
    def show
      add_breadcrumb t(:'hyrax.controls.home'), root_path
      add_breadcrumb t(:'hyrax.admin.sidebar.users'), proprietor_users_path
      add_breadcrumb @user.display_name, edit_proprietor_user_path(@user)
    end

    # GET /users/new
    def new
      add_breadcrumb t(:'hyrax.controls.home'), root_path
      add_breadcrumb t(:'hyrax.admin.sidebar.users'), proprietor_users_path
      add_breadcrumb 'New user', new_proprietor_user_path
    end

    # GET /users/1/edit
    def edit
      add_breadcrumb t(:'hyrax.controls.home'), root_path
      add_breadcrumb t(:'hyrax.admin.sidebar.users'), proprietor_users_path
      add_breadcrumb @user.display_name, edit_proprietor_user_path(@user)
    end

    # POST /users
    # POST /users.json
    def create
      @user = User.new(user_params)
      respond_to do |format|
        if @user.valid? && @user.save
          format.html { redirect_to proprietor_users_path, notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: [:proprietor, @user] }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to proprietor_users_path, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: [:proprietor, @user] }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
      message = if @user.destroy
                  'User was successfully destroyed.'
                else
                  'User could not be destroyed.'
                end

      respond_to do |format|
        format.html { redirect_to proprietor_users_url, notice: message }
        format.json { head :no_content }
      end
    end

    # method uses user's id, not their user_key
    def become
      bypass_sign_in(User.find(params[:id]))
      redirect_to root_url, notice: 'User changed successfully'
    end

    private

    def ensure_admin!
      authorize! :read, :admin_dashboard
    end

    # rubocop:disable Metrics/MethodLength
    def user_params
      # remove blank passwords
      params[:user].delete(:password) if params[:user] && params[:user][:password].blank?

      params.require(:user).permit(:email,
                                   :password,
                                   :superadmin,
                                   :facebook_handle,
                                   :twitter_handle,
                                   :googleplus_handle,
                                   :display_name,
                                   :address,
                                   :department,
                                   :title,
                                   :office,
                                   :chat_id,
                                   :website,
                                   :affiliation,
                                   :telephone,
                                   :avatar,
                                   :group_list,
                                   :linkedin_handle,
                                   :orcid,
                                   :arkivo_token,
                                   :arkivo_subscription,
                                   :zotero_token,
                                   :zotero_userid,
                                   :preferred_locale,
                                   role_ids: [])
    end
    # rubocop:enable Metrics/MethodLength

    def find_user
      @user ||= ::User.from_url_component(params[:id])
      raise ActiveRecord::RecordNotFound unless @user
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    skip_before_action :verify_authenticity_token

    def callback
      logger.info("=@=@=@=@  auth: #{request.env['omniauth.auth']}, params: #{params.inspect}")
      # Here you will need to implement your logic for processing the callback
      # for example, finding or creating a user
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        # We need to render a loading page here just to set the sesion properly
        # otherwise the logged in session gets lost during the redirect
        if params[:action] == 'saml'
          set_flash_message(:notice, :success, kind: params[:action]) if is_navigational_format?
          sign_in @user, event: :authentication # this will throw if @user is not activated
          render 'complete'
        else
          sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
          set_flash_message(:notice, :success, kind: params[:action]) if is_navigational_format?
        end
      else
        session['devise.user_attributes'] = @user.attributes
        redirect_to new_user_registration_url
      end
    end
    alias cas callback
    alias openid_connect callback
    alias saml callback

    def passthru
      render status: :not_found, plain: 'Not found. Authentication passthru.'
    end

    def failure
      redirect_to root_path, flash: { error: 'Authentication Failed. Something is wrong with the SSO configuration.' }
    end
  end
end

app/views/hyrax/admin/users/index.html.erb
<% if can? :create, User %>
  <% provide :page_header do %>
    <h1><span class="fa fa-user" aria-hidden="true"></span> <%= t('hyrax.admin.users.index.title') %></h1>
  <% end %>
<% else %>
  <% provide :page_header do %>
    <h1><span class="fa fa-user"></span> <%= t('hyrax.admin.users.index.reader_title') %></h1>
  <% end %>
<% end %>

<% if can? :create, User %>
  <div class="card users-invite">
    <div class="card-header">
        <%= t('.invite_users') %>
    </div>

    <div class="card-body">
      <%# user_invitation_path is provided by devise_invitable %>
      <%= simple_form_for :user,  url: main_app.user_invitation_path, html: { class: 'form-inline d-inline-flex' } do |f| %>
        <%= f.hint :email %>
        <div class="form-group">
          <%= f.label :email, class: "control-label", required: false %>
          <%= f.input_field :email, class: "form-control", value: "" %>
          <%= f.select :role,
                      @invite_roles_options.map { |r| [r.titleize, r ]},
                      { prompt: 'Select a role...' },
                      required: false,
                      class: 'form-control' %>
          <%= f.submit t('.add'), class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<div class="card users-listing">
  <div class="card-header">
      <%= t('hyrax.admin.users.index.describe_users_html', count: @presenter.user_count) %>
  </div>

  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-striped datatable">
        <thead>
          <tr>
            <th></th>
            <th><%= t('.id_label') %></th>
            <th><%= t('.group_label') %></th>
            <th><%= t('.group_role_label') %></th>
            <th><%= t('.site_role_label') %></th>
            <th><%= t('.access_label') %></th>
            <th><%= t('.status_label') %></th>
            <% if can? :destroy, User %>
            <th><%= t('.action_label') %></th>
            <% end %>
          </tr>
        </thead>
        <tbody id="manage-users-table">
          <% @presenter.users.each do |user| %>
            <tr id="<%= user.email.parameterize %>">
              <td><%= link_to hyrax.user_path(user) do %>
                    <%= image_tag(user.avatar.url(:thumb), width: 30) if user.avatar.file %>
                  <% end %>
              </td>
              <td><%= link_to user.email, hyrax.user_path(user) %></td>

              <td class="groups">
                <% groups = @presenter.user_groups(user) %>
                  <ul><% groups.each do |group| %>
                    <li><%= group.humanized_name %></li>
                    <% end %>
                  </ul>
              </td>

              <td class="group-roles"><% roles = @presenter.user_group_roles(user) %>
                  <ul><% roles.each do |role| %>
                    <li><%= role.name.titleize %></li>
                    <% end %>
                  </ul>
              </td>

              <td class="site-roles"><% roles = @presenter.user_site_roles(user) %>
                <ul>
                  <% roles.each do |role| %>
                    <li>
                      <%= role.name.titleize %>
                      <%= link_to main_app.remove_role_admin_user_path(id: user.id, role_id: role.id), method: :delete, data: { confirm: t('hyrax.admin.users.roles.remove.confirmation', user: user.email, role: role.name.titleize) } do %>
                        <% if current_ability.admin? || (can?(:edit, User) && role.name != 'admin') %>
                          <span class="fa fa-remove"></span>
                        <% end %>
                      <% end %>
                    </li>
                  <% end %>
                </ul>
              </td>

              <td>
                <%# in the case that a user is created who never signs in, this is necessary %>
                <relative-time datetime="<%= @presenter.last_accessed(user).getutc.iso8601 %>" title="<%= @presenter.last_accessed(user).to_formatted_s(:standard) %>">
                  <%= @presenter.last_accessed(user).to_formatted_s(:long_ordinal) %>
                </relative-time>
              </td>
              <%# If user accepted invite or was a self-signup, they are active. Otherwise pending %>
              <td><%= user.accepted_or_not_invited? ? t('.status.active') : t('.status.pending') %></td>
              <% if can? :destroy, User %>
                <td>
                  <%= link_to t('.delete'), main_app.admin_user_path(user), class: 'btn btn-danger btn-sm action-delete', method: :delete, data: { confirm: t('hyrax.admin.users.destroy.confirmation', user: user.email) } %>
                  <% if user.invited_to_sign_up? %>
                    <%= link_to t('.activate'), main_app.activate_admin_user_path(user.id), class: 'btn btn-primary btn-sm', method: :post, data: { confirm: t('hyrax.admin.users.activate.confirmation', user: user.email) } %>
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>